#!/bin/bash
# See skript küsib kasutajalt vanust ja väljastab vastava kasutaja tüübi.
#
# skripti algus
#
echo -n "Sisesta oma vanus: "
read vanus

if ((vanus >= 0 && vanus <= 11)); then
    echo "Oled laps"
elif ((vanus >= 12 && vanus <= 18)); then
    echo "Oled nooruk"
elif ((vanus >= 19 && vanus <= 63)); then
    echo "Oled täiskasvanu"
elif ((vanus >= 63)); then
    echo "Oled senjoor"
else
    echo "Vigane sisend. Sisesta vanus positiivse täisarvuna."
fi
#
# skripti l6pp
