#!/bin/bash
# See skript võimaldab kasutajal sisestada kuu numbri ja väljastab vastava aastaaja.
#
# skriptialgus
#
echo -n "Sisesta kuu number: "
read kuu

case $kuu in
    12|1|2)
        echo "Praegu on talv"
        ;;
    3|4|5)
        echo "Praegu on kevad"
        ;;
    6|7|8)
        echo "Praegu on suvi"
        ;;
    9|10|11)
        echo "Praegu on sügis"
        ;;
    *)
        echo "Vigane kuu number. Sisesta number vahemikus 1 kuni 12."
        ;;
esac
#
# skripti l6pp
