#!/bin/bash
# See skript tervitab kasutajat vastavalt sisestatud tunnile.
#
#skripti algus
#
echo -n "Sisesta aja väärtus (tundide arv): "
read tund

if ((tund >= 6 && tund < 12)); then
    echo "Tere hommikust"
elif ((tund >= 12 && tund < 18)); then
    echo "Tere päevast"
elif ((tund >= 18 && tund < 22)); then
    echo "Tere õhtust"
elif ((tund >= 22 || tund < 6)); then
    echo "Head ööd"
else
    echo "Vigane aja väärtus. Sisesta tundide arv vahemikus 0 kuni 23."
fi
#
# skripti l6pp
