#!/bin/bash

# skripti algus

# Küsime kasutajalt vanuse
read -p "Sisesta (oma) vanus: " vanus

# Kontrollime vanuse vahemikku ja väljastame vastava teate
if ((vanus >= 0)) && ((vanus <= 11)); then
    echo "Oled laps"
elif ((vanus >= 12)) && ((vanus <= 18)); then
    echo "Oled nooruk"
elif ((vanus >= 19)) && ((vanus <= 63)); then
    echo "Oled täiskasvanu"
elif ((vanus >= 64)); then
    echo "Oled senjoor"
else
    echo "Vigane sisend"
fi

# skripti l6pp
