#!/bin/bash
# Arvu numbride summa leidmine 
#
# skripti algus
#
echo -n "Sisesta suvaline täisarv: "
read arv
echo -n "Arvu $arv numbrite summa on"
#
if [ $arv -lt 0 ]; then
	arv=$(($arv * -1))
		echo -n "-"
fi
#
# Summa arvutamine
#
summa=0
while [$arv -ne 0]
do
	jääk=$(($arv % 10))
	summa=$(($summa + $jääk))
	arv=$(($arv / 10))
done
echo "$summa"
#
# skripti l6pp
