#!/bin/bash

# skripti algus

# Küsime kasutajalt ridade arvu ja tarnide arvu reas
read -p "Sisesta ridade arv: " reades
read -p "Sisesta tarnide arv reas: " symbols

# Väljastame tähekujundi
for ((i = 1; i <= reades; i++))
do
  for ((j = 1; j <= symbols; j++))
  do
    echo -n "* "
  done
  echo
done

# skripti l6pp
