#!/bin/bash

# skripti algus

# Küsime kasutajalt ridade arvu
read -p "Sisesta ridade arv: " reades

# Väljastame tähekujundi
for ((i = 1; i <= reades; i++))
do
  for ((j = 1; j <= i; j++))
  do
    echo -n "* "
  done
  echo
done

# skripti l6pp
